import type { Block } from 'payload'

export const CookiePreferences: Block = {
  slug: 'cookiePreferences',
  fields: [
    {
      name: 'buttonText',
      type: 'text',
      label: 'Manage cookies button text',
      required: true,
      defaultValue: 'Manage your cookie preferences',
      localized: true,
    },
    {
      name: 'consentText',
      type: 'text',
      label: 'Consent text',
      required: true,
      defaultValue: 'Consented',
      localized: true,
    },
    {
      name: 'declineText',
      type: 'text',
      label: 'Decline text',
      required: true,
      defaultValue: 'Declined',
      localized: true,
    },
    {
      name: 'essentialTitle',
      type: 'text',
      label: 'Essential cookies title',
      required: true,
      defaultValue: 'Essential',
      localized: true,
    },
    {
      name: 'essentialDescription',
      type: 'text',
      label: 'Essential cookies description',
      required: true,
      defaultValue: 'Required for the website to function properly',
      localized: true,
    },
    {
      name: 'analyticsTitle',
      type: 'text',
      label: 'Analytics cookies title',
      required: true,
      defaultValue: 'Analytics',
      localized: true,
    },
    {
      name: 'analyticsDescription',
      type: 'text',
      label: 'Analytics cookies description',
      required: true,
      defaultValue: 'Help us understand how visitors interact with our website',
      localized: true,
    },
    {
      name: 'socialTitle',
      type: 'text',
      label: 'Social cookies title',
      required: true,
      defaultValue: 'Social',
      localized: true,
    },
    {
      name: 'socialDescription',
      type: 'text',
      label: 'Social cookies description',
      required: true,
      defaultValue: 'Enable social media features and sharing',
      localized: true,
    },
    {
      name: 'advertisingTitle',
      type: 'text',
      label: 'Advertising cookies title',
      required: true,
      defaultValue: 'Advertising',
      localized: true,
    },
    {
      name: 'advertisingDescription',
      type: 'text',
      label: 'Advertising cookies description',
      required: true,
      defaultValue: 'Personalize advertisements and measure their performance',
      localized: true,
    },
  ],
  //   imageURL: 'https://iili.io/3AHY0cQ.md.png',
}
